apiVersion: v1
kind: Pod
metadata:
  name: online-inference-ml-probs
  labels:
    app: online-inference-ml-probs
spec:
  containers:
    - image: nickml/online_inference:v1
      name: online-inference-ml-probs
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8000
        failureThreshold: 1
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 3
      startupProbe:
        httpGet:
          path: /healthz
          port: 8000
        failureThreshold: 3
        periodSeconds: 10
