apiVersion: v1
kind: Pod
metadata:
  name: online-inference-ml
  labels:
    app: online-inference-ml
spec:
  containers:
    - image: nickml/online_inference:v1
      name: online-inference-ml
      ports:
        - containerPort: 8000
